---
namespace: trippsc2
name: general
version: 2.10.1
readme: README.md
authors:
  - Jim Tarpley (@trippsc2)
description: This collection contains general purpose Ansible plugins.

license_file: 'LICENSE'

tags:
  - infrastructure
  - tools

dependencies:
  ansible.windows: '>=1.0.0'
  community.crypto: '>=1.0.0'
  google.cloud: '>=1.0.0'

repository: https://github.com/trippsoft/ansible-collection-general.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
