---
name: Molecule - combine_certificates module plugin
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - galaxy.yml
      - plugins/modules/combine_certificates.py
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - plugins/modules/combine_certificates.py
defaults:
  run:
    working-directory: 'trippsc2.general'
jobs:
  molecule:
    name: Run Molecule tests
    runs-on:
      - self-hosted
      - linux
      - x64
    strategy:
      fail-fast: false
      matrix:
        box:
          - debian12_base
          - fedora42_base
          - fedora41_base
          - rocky9_cis
          - rocky8_cis
          - ubuntu2404_base
          - ubuntu2204_base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'trippsc2.general'
      - name: Run Molecule tests
        run: |
          source ~/venv/ansible-2.16/bin/activate
          rm -rf ~/.ansible/collections/ansible_collections/*
          molecule test -s combine_certificates
          rm -rf ~/.ansible/collections/ansible_collections/*
          deactivate
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PY_COLORS: '1'
          MOLECULE_BOX: ${{ matrix.box }}
